name: Ensure Latest Ref
description: 'Ensures a ref is the latest ref for a PR. This should be run after every checkout for a PR branch to ensure we are only interacting with trusted changes.'
inputs:
  ref:
    description: "The git commit we are ensuring is the latest"
    required: true
runs:
  using: "composite"
  steps:
    - name: ensure latest ref
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: ${{ !(github.event.client_payload.pull_request.head.sha != '' && 
            contains(github.event.client_payload.pull_request.head.sha, inputs.sha)
          ) }}           
      with:
        script: core.setFailed('Ref is not latest')
