# adapted from https://github.com/Azure/karpenter-provider-azure/blob/main/.github/actions/commit-status/end/action.yaml

name: End Status
description: 'Adds a commit status at the end of the test run based on success, failure, or cancelled'
inputs:
  name:
    description: "Name of the check"
    required: true
  ref:
    description: "The git commit, tag, or branch to check out"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: job.status == 'success'
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            context: "${{ inputs.name }}",
            sha: "${{ inputs.ref }}",
            state: "success",
            target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          });
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: job.status == 'failure' || job.status == 'cancelled'
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            context: "${{ inputs.name }}",
            sha: "${{ inputs.ref }}",
            state: "failure",
            target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          });