version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group updates together, so that they are all applied in a single PR.
      # Grouped updates are currently in beta and is subject to change.
      # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      k8s-go-deps:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "github.com/open-policy-agent/*"
      go-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "github.com/open-policy-agent/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"