# This file contains a minimal cluster role for the operator.
# It's tested as part of the operator's e2e tests, so it can be trusted to provide sufficient privileges.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-app-routing-operator
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "clusterroles"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["namespaces", "configmaps", "services", "events", "serviceaccounts"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["*"]

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]

  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]

  - apiGroups: ["secrets-store.csi.x-k8s.io"]
    resources: ["secretproviderclasses"]
    verbs: ["*"]

  - apiGroups: ["policy.openservicemesh.io"]
    resources: ["ingressbackends"]
    verbs: ["*"]

  - apiGroups: ["config.openservicemesh.io"]
    resources: ["meshconfigs"]
    verbs: ["*"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
