#!/usr/bin/env bash
set -e

source ./devenv/scripts/command_invoke_with_output.sh

# Load variables generated by tf
export CLUSTER_CLIENT_ID=$(cat devenv/state/deployment-auth-info.json | jq '.ClusterClientId' | tr -d '"')
export ARM_CLIENT_TENANT_ID=$(cat devenv/state/deployment-auth-info.json | jq '.ArmTenantId' | tr -d '"')
export RG_LOCATION=$(cat devenv/state/deployment-auth-info.json | jq '.ResourceGroupLocation' | tr -d '"')
export DNS_ZONE_IDS=$(cat devenv/state/deployment-auth-info.json | jq '.DnsZones' | tr -d '"')
export CLUSTER_FQDN=$(cat devenv/state/deployment-auth-info.json | jq '.ClusterFqdn' | tr -d '"')

# move into state before envsubst
mkdir -p devenv/state/kustomize/operator-deployment
cp devenv/kustomize/operator-deployment/* devenv/state/kustomize/operator-deployment

# Write env to kustomize patch
envsubst < devenv/kustomize/operator-deployment/kustomization.yaml > devenv/state/kustomize/operator-deployment/kustomization.yaml

# Get cluster information for az aks command invoke
CLUSTER_RESOURCE_GROUP=$(cat devenv/state/cluster-info.json | jq '.ClusterResourceGroup' | tr -d '"')
CLUSTER_NAME=$(cat devenv/state/cluster-info.json | jq '.ClusterName' | tr -d '"')

echo "deploying to ${CLUSTER_NAME} in resource group ${CLUSTER_RESOURCE_GROUP}"
cd devenv/state/kustomize/operator-deployment

APPLY_RESULT=$(run_invoke $CLUSTER_NAME $CLUSTER_RESOURCE_GROUP "kubectl apply -k ." ".")
