apiVersion: batch/v1
kind: Job
metadata:
  name: app-routing-operator-e2e
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: app-routing-operator-e2e
    spec:
      containers:
        - name: tester
          image: placeholderfortesterimage
          command: [ "/bin/sh" ]
          args: [ "/go/src/github.com/Azure/aks-app-routing-operator/devenv/scripts/make_run_e2e.sh" ]
      restartPolicy: Never
  backoffLimit: 2
