# adapted from https://github.com/Azure/karpenter-provider-azure/blob/main/.github/actions/commit-status/start/action.yaml

name: Start Status
description: 'Adds a commit status at the start of the test run to set the status to pending'
inputs:
  name:
    description: "Name of the check"
    required: true
  ref:
    description: "The git commit, tag, or branch to check out"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      if: always()
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            context: "${{ inputs.name }}",
            sha: "${{ inputs.ref }}",
            state: "pending",
            target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          });