name: E2E Version 2 Provision and Test

on:
  workflow_call:
    inputs:
      ref:
        type: string
      skipRefCheck:
        type: boolean
        default: true
      name:
        type: string
        required: true

permissions:
  id-token: write

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@v4
        with:
          go-version: '~1.20.3'
          cache-dependency-path: "**/*.sum"

      - name: install azure-cli 2.58.0 # needed due to az cli regression https://github.com/Azure/login/issues/372. We need to remove this when az cli 2.60 is released and baked into runner image
        # install steps from https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
              sudo gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg
          sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
          AZ_DIST=$(lsb_release -cs)
          echo "Types: deb
          URIs: https://packages.microsoft.com/repos/azure-cli/
          Suites: ${AZ_DIST}
          Components: main
          Architectures: $(dpkg --print-architecture)
          Signed-by: /etc/apt/keyrings/microsoft.gpg" | sudo tee /etc/apt/sources.list.d/azure-cli.sources
          AZ_VER=2.58.0
          sudo apt-get update && sudo apt-get install azure-cli=${AZ_VER}-1~${AZ_DIST} --allow-downgrades

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        shell: bash
        run: (cd testing/e2e && go run ./main.go infra --subscription="${{ secrets.AZURE_SUBSCRIPTION_ID }}" --tenant="${{ secrets.AZURE_TENANT_ID }}" --names="${{ inputs.name }}" --infra-file="./infra.json")
        if: # avoids race condition security vulnerability by ensuring we are only running changes that were /ok-to-test'd
          (github.event_name == 'repository_dispatch' &&
          github.event.client_payload.slash_command.args.named.sha != '' &&
          contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.args.named.sha)) ||
          inputs.skipRefCheck

      - name: Ensure ref
        uses: actions/github-script@v6
        if: ${{ !((github.event_name == 'repository_dispatch' && github.event.client_payload.slash_command.args.named.sha != '' && contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.args.named.sha)) || inputs.skipRefCheck) }}
        with:
          script: core.setFailed('Ref is not latest')

      - name: Upload infra file
        uses: actions/upload-artifact@v3
        with:
          name: infra
          path: testing/e2e/infra.json
  test:
    needs: provision
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@v4
        with:
          go-version: '~1.20.3'

      - name: install azure-cli 2.58.0 # needed due to az cli regression https://github.com/Azure/login/issues/372. We need to remove this when az cli 2.60 is released and baked into runner image
        # install steps from https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
              sudo gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg
          sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
          AZ_DIST=$(lsb_release -cs)
          echo "Types: deb
          URIs: https://packages.microsoft.com/repos/azure-cli/
          Suites: ${AZ_DIST}
          Components: main
          Architectures: $(dpkg --print-architecture)
          Signed-by: /etc/apt/keyrings/microsoft.gpg" | sudo tee /etc/apt/sources.list.d/azure-cli.sources
          AZ_VER=2.58.0
          sudo apt-get update && sudo apt-get install azure-cli=${AZ_VER}-1~${AZ_DIST} --allow-downgrades

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: infra
          path: testing/e2e/

      - name: Test
        shell: bash
        id: test
        run: (cd testing/e2e && go run ./main.go deploy --infra-file="./infra.json")
        if:
          (github.event_name == 'repository_dispatch' &&
          github.event.client_payload.slash_command.args.named.sha != '' &&
          contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.args.named.sha)) ||
          inputs.skipRefCheck

      - name: Print test logs
        shell: bash
        run: echo "printing first 100 lines and last 200 lines of e2e logs..." && head -n 100 testing/e2e/job-app-routing-operator-e2e.log && tail -n 200 testing/e2e/job-app-routing-operator-e2e.log
        if: always() && (steps.test.outcome == 'failure' || steps.test.outcome == 'success')

      - name: Ensure ref
        uses: actions/github-script@v6
        if: ${{ !((github.event_name == 'repository_dispatch' && github.event.client_payload.slash_command.args.named.sha != '' && contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.args.named.sha)) || inputs.skipRefCheck) }}
        with:
          script: core.setFailed('Ref is not latest')
