name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release. Must be in the CHANGELOG.md file. Example: 1.0.0'
        required: true

permissions:
      id-token: write
      contents: read

jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read changelog
        id: changelog
        uses: mindsers/changelog-reader-action@b97ce03a10d9bdbb07beb491c76a5a01d78cd3ef # v2.2.2
        with:
          version: ${{ inputs.version }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image
        run: |
          TAG="${{ secrets.AZURE_REGISTRY_SERVER }}/public/aks/aks-app-routing-operator:sha-$(git rev-parse --short HEAD)"
          az acr login -n ${{ secrets.AZURE_REGISTRY_SERVER }}
          docker buildx build --platform "amd64,arm64" --tag "${TAG}" --output type=registry .

      - name: Create or update release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1.12.0
        with:
          name: v${{ steps.changelog.outputs.version }}
          tag: v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          prerelease: false
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
